import type { ProgrammeKind } from '../types';

/**
 * THE PROGRAMMING. This is the other file to edit.
 *
 * Each entry is one channel and the segments that rotate on it. Segments are
 * text — the compositor paints them onto the CRT, styled according to the
 * channel's `kind`.
 *
 * Keep lines short. This renders at 640x480 behind scanlines; much over ~70
 * characters wraps and starts to look like a slide deck rather than television.
 *
 * Channel 10, LIBRARY, is not here — it is generated from `books.data.ts` in
 * `channels.ts`. Add a book and it is on television without touching this file.
 *
 * To broadcast a real video instead of a text card, give a programme a `media`
 * object (see `Programme` in src/types.ts). Everything else — the schedule, the
 * captions, the shader — keeps working unchanged.
 */

export type ProgrammeData = {
  heading: string;
  subheading: string;
  lines: string[];
  footer: string;
  durationSec: number;
};

export type ChannelData = {
  num: number;
  slug: string;
  name: string;
  kind: ProgrammeKind;
  programmes: ProgrammeData[];
};

export const CHANNEL_DATA: ChannelData[] = [
  {
    num: 2,
    slug: "poetry",
    name: "POETRY",
    kind: "poem",
    programmes: [
      {
        heading: "WILD NIGHTS - WILD NIGHTS!",
        subheading: "Emily Dickinson, written c. 1861",
        lines: [
          "Wild nights - Wild nights!",
          "Were I with thee",
          "Wild nights should be",
          "Our luxury!",
          "",
          "Futile - the winds -",
          "To a Heart in port -",
          "Done with the Compass -",
          "Done with the Chart!",
          "",
          "Rowing in Eden -",
          "Ah - the Sea!",
          "Might I but moor - tonight -",
          "In thee!",
        ],
        footer: "Found in a drawer. Not printed until 1891.",
        durationSec: 26,
      },
      {
        heading: "THE SICK ROSE",
        subheading: "William Blake, Songs of Experience, 1794",
        lines: [
          "O Rose thou art sick.",
          "The invisible worm,",
          "That flies in the night",
          "In the howling storm:",
          "",
          "Has found out thy bed",
          "Of crimson joy:",
          "And his dark secret love",
          "Does thy life destroy.",
        ],
        footer: "Blake etched the plate himself and coloured every copy by hand.",
        durationSec: 19,
      },
      {
        heading: "FRAGMENT 31",
        subheading: "Sappho, c. 600 BC - tr. Henry Thornton Wharton, 1885",
        lines: [
          "That man seems to me peer of gods, who sits",
          "in thy presence, and hears close to him",
          "thy sweet speech and lovely laughter;",
          "that indeed makes my heart flutter in my bosom.",
          "For when I see thee but a little, I have no",
          "utterance left, my tongue is broken down,",
          "and straightway a subtle fire has run under my skin,",
          "with my eyes I have no sight, my ears ring,",
          "sweat pours down, and a trembling seizes all my body;",
          "I am paler than grass, and seem in my madness",
          "little better than one dead.",
        ],
        footer: "It survives only because a Greek critic quoted it as an example of the sublime.",
        durationSec: 35,
      },
      {
        heading: "DRINKING ALONE BY MOONLIGHT",
        subheading: "Li Po, c. AD 750 - tr. Arthur Waley, 1919",
        lines: [
          "A cup of wine, under the flowering trees;",
          "I drink alone, for no friend is near.",
          "Raising my cup I beckon the bright moon,",
          "For he, with my shadow, will make three men.",
          "The moon, alas, is no drinker of wine;",
          "Listless, my shadow creeps about at my side.",
          "Yet with the moon as friend and the shadow as slave",
          "I must make merry before the Spring is spent.",
          "To the songs I sing the moon flickers her beams;",
          "In the dance I weave my shadow tangles and breaks.",
          "While we were sober, three shared the fun;",
          "Now we are drunk, each goes his way.",
          "May we long share our odd, inanimate feast,",
          "And meet at last on the Cloudy River of the sky.",
        ],
        footer: "The Cloudy River is the Milky Way.",
        durationSec: 38,
      },
      {
        heading: "TWO VERSES FROM OLD JAPAN",
        subheading: "tr. William N. Porter, 1909",
        lines: [
          "Long is the mountain pheasant's tail",
          "That curves down in its flight;",
          "But longer still, it seems to me,",
          "Left in my lonely plight,",
          "Is this unending night.",
          "    - Kakinomoto no Hitomaro",
          "",
          "The blossom's tint is washed away",
          "By heavy showers of rain;",
          "My charms, which once I prized so much,",
          "Are also on the wane, -",
          "Both bloomed, alas! in vain.",
          "    - Ono no Komachi",
        ],
        footer: "From the Hyakunin Isshu, one hundred poets, one poem each.",
        durationSec: 31,
      },
      {
        heading: "PIED BEAUTY",
        subheading: "Gerard Manley Hopkins, 1877",
        lines: [
          "Glory be to God for dappled things -",
          "For skies of couple-colour as a brinded cow;",
          "For rose-moles all in stipple upon trout that swim;",
          "Fresh-firecoal chestnut-falls; finches' wings;",
          "Landscape plotted and pieced - fold, fallow, and plough;",
          "And all trades, their gear and tackle and trim.",
          "",
          "All things counter, original, spare, strange;",
          "Whatever is fickle, freckled (who knows how?)",
          "With swift, slow; sweet, sour; adazzle, dim;",
          "He fathers-forth whose beauty is past change:",
          "Praise him.",
        ],
        footer: "Written in Wales. Nobody read it for forty-one years.",
        durationSec: 31,
      },
      {
        heading: "I AM",
        subheading: "John Clare, written c. 1845",
        lines: [
          "I am - yet what I am none cares or knows;",
          "My friends forsake me like a memory lost:",
          "I am the self-consumer of my woes -",
          "They rise and vanish in oblivious host,",
          "Like shadows in love's frenzied stifled throes",
          "And yet I am, and live - like vapours tossed",
          "",
          "Into the nothingness of scorn and noise,",
          "Into the living sea of waking dreams,",
          "Where there is neither sense of life or joys,",
          "But the vast shipwreck of my life's esteems;",
          "Even the dearest that I loved the best",
          "Are strange - nay, rather, stranger than the rest.",
        ],
        footer: "Stanzas one and two of three, written in the Northampton asylum.",
        durationSec: 33,
      },
    ],
  },
  {
    num: 3,
    slug: "cinema",
    name: "CINEMA",
    kind: "scene",
    programmes: [
      {
        heading: "The Night of the Hunter",
        subheading: "Charles Laughton, 1955",
        lines: [
          "Uncle Birdie rows out at first light to check his lines.",
          "Below the hull, in green water, Willa sits upright in the car.",
          "Her throat is open. Her hair drifts out with the river weed.",
          "Laughton frames it as still life, not horror. No music sting,",
          "no cut to a screaming face. The camera looks, and keeps looking.",
          "The loveliest image of a murder in American film,",
          "which is precisely what makes it obscene.",
        ],
        footer: "",
        durationSec: 34,
      },
      {
        heading: "Playtime",
        subheading: "Jacques Tati, 1967",
        lines: [
          "A doorman swings the restaurant's glass door too hard and it",
          "explodes into nothing. He is left holding the brass handle.",
          "So he keeps working: bowing, opening the empty air,",
          "and the guests keep pretending to pass through the door.",
          "Tati never cuts in for the gag. It plays far back in a wide",
          "frame, competing with four other jokes for your eye.",
          "You have to find it yourself, which is why it stays funny.",
        ],
        footer: "",
        durationSec: 32,
      },
      {
        heading: "Touki Bouki",
        subheading: "Djibril Diop Mambety, 1973",
        lines: [
          "Mory's motorbike wears the horns of a zebu. He rides it to",
          "the cliff at Dakar, and he and Anta lie down above the sea.",
          "Mambety cuts their bodies against surf, against the abattoir,",
          "against a boat named for Paris that they mean to be on.",
          "The song under it is Josephine Baker, singing of Paris,",
          "over a country the film refuses to make picturesque.",
          "Colonial dream and slaughterhouse, edited into one pulse.",
        ],
        footer: "",
        durationSec: 34,
      },
      {
        heading: "The Ascent",
        subheading: "Larisa Shepitko, 1977",
        lines: [
          "Occupied Belarus. Five prisoners walk to the gallows through",
          "snow, past a village that has been made to watch.",
          "Shepitko shoots Sotnikov's last minutes in close-up, lit like",
          "an icon, and keeps finding one boy's face in the crowd.",
          "The film has argued about the soul for two hours.",
          "Here it stops arguing and simply holds on a face",
          "until the face becomes the argument, and the boy inherits it.",
        ],
        footer: "I am a partisan. The rest have done nothing.",
        durationSec: 36,
      },
      {
        heading: "A Brighter Summer Day",
        subheading: "Edward Yang, 1991",
        lines: [
          "A typhoon has taken the power out. The Little Park Boys walk",
          "into the 217 gang's pool hall with knives and a flashlight",
          "stolen from a film studio.",
          "Yang films the killing almost entirely in the dark, in wides,",
          "from down the corridor. You hear more than you see.",
          "The one clean light in the frame is a prop, taken from a set",
          "where grown men were pretending. Nothing here is pretending.",
        ],
        footer: "",
        durationSec: 36,
      },
      {
        heading: "Cure",
        subheading: "Kiyoshi Kurosawa, 1997",
        lines: [
          "The suspect holds no thought for ten seconds. He only asks.",
          "Who are you? Tell me about yourself. What do you do?",
          "A lighter flame does the rest. Or water running in a sink.",
          "Kurosawa shoots from the corner of the room, one long take,",
          "at a cold distance, with no reaction shot to tell you when",
          "a person has been emptied out.",
          "By the time you notice, the emptying is already finished.",
        ],
        footer: "Who are you? Tell me about yourself.",
        durationSec: 32,
      },
      {
        heading: "Uncle Boonmee",
        subheading: "Apichatpong Weerasethakul, 2010",
        lines: [
          "The film stops and, for fifteen minutes, becomes a folk tale.",
          "A disfigured princess is carried by litter to a waterfall,",
          "sees a young beauty in the water that is not her face,",
          "and lowers herself in to be loved by a talking catfish.",
          "It is shot plainly, in daylight, no wink, no swelling music.",
          "Apichatpong declines to mark any of it as fantasy,",
          "so it lands with the flat authority of something remembered.",
        ],
        footer: "",
        durationSec: 36,
      },
    ],
  },
  {
    num: 4,
    slug: "music",
    name: "MUSIC",
    kind: "track",
    programmes: [
      {
        heading: "Left Alone",
        subheading: "Mal Waldron, 1959",
        lines: [
          "Waldron spent Billie Holiday's last two years as her pianist.",
          "He wrote this melody. She wrote a lyric and never sang it.",
          "Recorded in 1959, the year she died.",
          "Jackie McLean states the tune on alto and cannot let it go —",
          "the tone splinters, comes back, splinters again.",
          "Underneath, Waldron plays the same dark chord until it hurts.",
        ],
        footer: "The grief is in the piano, not the horn.",
        durationSec: 32,
      },
      {
        heading: "24 Track Loop",
        subheading: "This Heat, 1979",
        lines: [
          "Recorded in a disused cold store inside a Brixton pie factory.",
          "The band called it Cold Storage and lived in it for years.",
          "Drums were cut to tape, looped, fed back through the desk",
          "until the loop stopped being a trick and became the piece.",
          "This is 1976 to 1978. No samplers existed. Razor blades did it.",
          "They invented most of the next thirty years by accident.",
        ],
        footer: "One of the three had never played an instrument when he joined.",
        durationSec: 33,
      },
      {
        heading: "Bhar Do Jholi Meri",
        subheading: "The Sabri Brothers, 1975",
        lines: [
          "Karachi brothers who carried qawwali into Western concert halls.",
          "Harmonium, tabla, and a row of men clapping in unison.",
          "The title asks the Prophet to fill an empty begging bowl.",
          "It opens conversationally and takes forty minutes to arrive,",
          "tightening one notch at a time and never slackening.",
          "The chorus repeats one line until it stops being repetition.",
        ],
        footer: "Qawwali is not a concert. It is a petition, sung aloud.",
        durationSec: 32,
      },
      {
        heading: "Pick a Dub",
        subheading: "Keith Hudson, 1974",
        lines: [
          "Hudson trained as a dental technician before he cut records.",
          "Same instinct: take things out, see what still holds.",
          "The Barrett brothers lay the riddim, and the mix removes it —",
          "down to bass, one snare crack, and a room made of echo.",
          "A vocal surfaces for a single word and is swallowed whole.",
          "Most dub was assembled from leftovers. This was built as an album.",
        ],
        footer: "Kingston, 1974. Empty space, played as an instrument.",
        durationSec: 31,
      },
      {
        heading: "Blink",
        subheading: "Hiroshi Yoshimura, 1982",
        lines: [
          "Made at home on a Fender Rhodes and one synthesiser,",
          "as a demo tape offered to the Hara Museum in Tokyo.",
          "They kept it and played it in the galleries for years.",
          "Two or three notes at a time, a long decay, then room.",
          "Yoshimura also wrote music for train stations and houses.",
          "He wanted sound you notice the way you notice light moving.",
        ],
        footer: "Nothing here asks for your attention. All of it rewards it.",
        durationSec: 30,
      },
      {
        heading: "Heaven",
        subheading: "Ebo Taylor, 1980",
        lines: [
          "Taylor was in London in the sixties, in the same student circles",
          "as a young Fela Kuti. Then home to Accra, to slow highlife down.",
          "The guitar figure lands in bar one and never leaves.",
          "Horns answer in thirds. Nothing hurries. Nothing resolves.",
          "Unheard outside Ghana for thirty years, until a sample carried it",
          "into an American hit and Taylor toured the world in his seventies.",
        ],
        footer: "Patience, played by a band that had plenty of it.",
        durationSec: 33,
      },
      {
        heading: "Stay On It",
        subheading: "Julius Eastman, 1973",
        lines: [
          "One bright riff, repeated, handed around the ensemble —",
          "among the first minimalist works to admit it liked pop music.",
          "Then it begins coming apart. Players drift, shout, drop out.",
          "What is left at the end is almost nothing, and it levels you.",
          "Eastman was Black, gay, brilliant, and unhoused by the eighties.",
          "His scores went into the street. He died in 1990, aged 49.",
        ],
        footer: "This piece exists today because somebody kept a tape.",
        durationSec: 34,
      },
    ],
  },
  {
    num: 5,
    slug: "critters",
    name: "CRITTERS",
    kind: "critter",
    programmes: [
      {
        heading: "THE PANGOLIN",
        subheading: "Armoured, toothless, and made largely of hair",
        lines: [
          "Its scales are keratin - the same material as your fingernails.",
          "It has no teeth at all. It swallows small stones instead,",
          "and grinds the ants in a gizzard, the way a bird does.",
          "Its tongue is anchored down near the pelvis, and unrolled it is",
          "longer than the animal's head and body put together.",
          "Rolled into a ball, it has been filmed shrugging off lions.",
        ],
        footer: "It is also the most trafficked wild mammal on Earth.",
        durationSec: 28,
      },
      {
        heading: "THE TARDIGRADE",
        subheading: "Half a millimetre long. Survived open space.",
        lines: [
          "When things go wrong it expels almost all of its water,",
          "folds in its eight legs, and becomes a barrel called a tun.",
          "In 2007 the FOTON-M3 satellite carried dried tardigrades",
          "on its outer hull: hard vacuum, cosmic radiation, solar UV.",
          "Ten days later they came home, were rewetted, and laid eggs.",
          "They are not indestructible, though. Squashing works fine.",
        ],
        footer: "Common names: water bear. Also, moss piglet.",
        durationSec: 30,
      },
      {
        heading: "THE SUPERB LYREBIRD",
        subheading: "Australia's finest liar",
        lines: [
          "It has the most complex vocal organ of any songbird,",
          "and uses it almost entirely to impersonate other birds.",
          "Captive ones have added chainsaws, drills, camera shutters.",
          "In 2021 scientists caught the male at something stranger:",
          "while mating, he mimics an entire flock of panicking birds -",
          "wingbeats included. A predator that isn't there. So she stays.",
        ],
        footer: "Played back in the forest, the fake flock fools real birds.",
        durationSec: 32,
      },
      {
        heading: "INKY THE OCTOPUS",
        subheading: "National Aquarium of New Zealand, April 2016",
        lines: [
          "Staff left the lid of his tank slightly ajar overnight.",
          "Inky climbed out and crossed the floor. In the morning",
          "there were wet tracks leading away from the glass.",
          "He had found a drainpipe, 150mm wide and 50 metres long,",
          "gone down it, and come out in Hawke's Bay.",
          "An octopus fits through any gap wider than its beak.",
        ],
        footer: "Blotchy, the other octopus in the tank, stayed home.",
        durationSec: 30,
      },
      {
        heading: "THE SEA OTTER",
        subheading: "No blubber. Nothing but fur and appetite.",
        lines: [
          "It has no fat layer at all. Instead: up to a million hairs",
          "per square inch, the densest coat of any animal alive.",
          "To sleep, it wraps itself in kelp so the tide cannot take it,",
          "or holds paws with the next otter so the raft stays together.",
          "Under each foreleg is a loose pouch of skin - for shellfish,",
          "and for a favourite rock, carried from one meal to the next.",
        ],
        footer: "It eats a quarter of its own body weight every day.",
        durationSec: 32,
      },
      {
        heading: "THE DUNG BEETLE",
        subheading: "It steers by the galaxy",
        lines: [
          "A dung beetle must roll its ball in a dead straight line,",
          "away from the thieves at the pile. Wobble and you lose it.",
          "On moonless nights it still holds a perfect course.",
          "So researchers glued tiny caps on them, blocking the sky,",
          "then ran the whole thing inside a Johannesburg planetarium.",
          "Milky Way on: straight. Stars off: circles.",
        ],
        footer: "The first animal ever found navigating by the galaxy. 2013.",
        durationSec: 32,
      },
      {
        heading: "THE MANTIS SHRIMP",
        subheading: "Four inches long. Punches like a bullet.",
        lines: [
          "The club on its foreleg is spring-loaded and held by a latch.",
          "Released, it accelerates like a .22 round and arrives",
          "in under three thousandths of a second.",
          "It moves so fast the water behind it boils into a bubble,",
          "and when the bubble collapses, the prey is hit a second time.",
          "Aquarium keepers have had tank glass cracked by one.",
        ],
        footer: "It has up to 16 kinds of colour receptor. You have three.",
        durationSec: 30,
      },
    ],
  },
  {
    num: 6,
    slug: "latenight",
    name: "LATE NIGHT",
    kind: "monologue",
    programmes: [
      {
        heading: "UNEXPECTED ITEM",
        subheading: "In the Bagging Area",
        lines: [
          "The machine says: unexpected item in the bagging area.",
          "It is a banana. I put it there. On purpose.",
          "Nothing here was unexpected except its reaction.",
          "A teenager in a vest taps the screen twice and walks off.",
          "He performed a miracle and did not stay for the credits.",
          "I would like to be forgiven that fast for anything.",
        ],
        footer: "Please wait for assistance.",
        durationSec: 27,
      },
      {
        heading: "OUT OF MAGENTA",
        subheading: "A Printer Speaks",
        lines: [
          "The printer says it cannot print. It is out of magenta.",
          "I am printing a lease. In black. On white paper.",
          "It knows this. It has decided this is the hill.",
          "I have not printed in color since a wedding in 2019.",
          "The magenta ran out in solidarity with something.",
          "A document is being held hostage over a color no one asked for.",
        ],
        footer: "Cancel. Cancel. Cancel. Now printing 40 copies.",
        durationSec: 28,
      },
      {
        heading: "THE GROUP CHAT",
        subheading: "Nine People, One Purpose",
        lines: [
          "Someone asked a real question at nine in the morning.",
          "Six people saw it. Nobody answered. It sat there all day.",
          "At four, someone posted a photo of a dog in a hat.",
          "Eleven replies in forty seconds. Two of them were mine.",
          "The question is still up there, holding the ceiling up.",
          "We are not friends. We are a delivery system for that dog.",
        ],
        footer: "Sarah is typing. Sarah has stopped typing.",
        durationSec: 28,
      },
      {
        heading: "THE MAN AT THE DOOR",
        subheading: "A Commuting Story",
        lines: [
          "Same train, same car, same door, every single morning.",
          "There is a man who stands exactly where I stand.",
          "We have never spoken. We are at war.",
          "This morning he was not there. I won.",
          "I have never felt worse about anything in my life.",
          "I hope he is well. I hope he knows the result.",
        ],
        footer: "Mind the gap.",
        durationSec: 26,
      },
      {
        heading: "BACK IN THE TWENTY-TENS",
        subheading: "On the Passage of Time",
        lines: [
          "I still describe 2015 as a couple of years ago.",
          "There is a song I call the new one. It is from 2009.",
          "Someone said back in the twenty-tens and I had to sit down.",
          "The decade got a name. Nobody ran it past me.",
          "My references have quietly become period detail.",
          "I am not aging. I am being referred to in the past tense.",
        ],
        footer: "That was the news. It was a while ago.",
        durationSec: 27,
      },
      {
        heading: "THE CHIRP",
        subheading: "Three in the Morning",
        lines: [
          "The smoke detector chirps once every sixty seconds.",
          "Not an alarm. A chirp. A hint.",
          "It waited two years, then chose 3 a.m. to have needs.",
          "I am on a kitchen chair in the dark, arguing with a ceiling.",
          "New battery. Silence. I get back into bed.",
          "It chirps once more to confirm. That one was for sport.",
        ],
        footer: "Test monthly. Replace annually. Sleep never.",
        durationSec: 28,
      },
      {
        heading: "STILL UP",
        subheading: "You, Right Now",
        lines: [
          "It is two in the morning. You meant to sleep at eleven.",
          "You are not doing anything. You are just not stopping.",
          "You have read the same paragraph four times. It is a menu.",
          "Tomorrow you will feel awful and you will blame tomorrow.",
          "Tomorrow had nothing to do with it.",
          "Goodnight. Or whatever it is we are calling this.",
        ],
        footer: "LATE NIGHT continues after this.",
        durationSec: 25,
      },
    ],
  },
  {
    num: 7,
    slug: "science",
    name: "SCIENCE",
    kind: "fact",
    programmes: [
      {
        heading: "The Static Was The Big Bang",
        subheading: "Cosmic microwave background, found 1964",
        lines: [
          "Tune an analog set to a dead channel and it fills with snow.",
          "Most of that is noise in the receiver, or signals close by.",
          "But a small share is light from 13.8 billion years ago,",
          "the moment the cooling universe first turned transparent.",
          "That glow was once 3,000 degrees. Space stretched it to 2.7.",
          "It falls in from every direction, always. Even now. Even here.",
        ],
        footer: "Penzias and Wilson first blamed pigeon droppings.",
        durationSec: 32,
      },
      {
        heading: "The Sun Is A Poor Furnace",
        subheading: "The proton-proton chain, Bethe, 1939",
        lines: [
          "The core runs at 15 million degrees. That is not hot enough.",
          "Two protons repel far too strongly to ever meet and fuse.",
          "They fuse anyway, tunneling through a wall they cannot climb.",
          "Even so the odds are dreadful: a proton waits billions of years.",
          "Per cubic meter the core gives off less heat than a compost pile.",
          "The Sun is fierce only because the Sun is enormous.",
        ],
        footer: "It has been doing this for 4.6 billion years.",
        durationSec: 32,
      },
      {
        heading: "There Is A Motor In Every Cell",
        subheading: "ATP synthase, the smallest rotary engine known",
        lines: [
          "Your mitochondria pump protons out across a membrane.",
          "The protons crowd, and push back, and the only way in",
          "is through a molecular turbine anchored in that wall.",
          "It turns at over a hundred revolutions a second,",
          "and each full turn snaps out three molecules of ATP.",
          "You build and spend near your own body weight in ATP daily.",
        ],
        footer: "We know because someone watched a single one spin.",
        durationSec: 30,
      },
      {
        heading: "The Day Used To Be Shorter",
        subheading: "Tidal friction, written into coral",
        lines: [
          "Tides drag against the spinning Earth and slow it down.",
          "The lost momentum goes to the Moon, which drifts away",
          "by 3.8 centimeters a year. Apollo left mirrors to prove it.",
          "Corals lay a growth band each day, and a wider one each year.",
          "Devonian corals show 400 days packed into a single orbit.",
          "The day ran near 22 hours. The first forests were rising.",
        ],
        footer: "The Moon is farther off now than when you were born.",
        durationSec: 32,
      },
      {
        heading: "Why You Do Not Fall Through The Floor",
        subheading: "The Pauli exclusion principle",
        lines: [
          "Atoms are almost entirely empty. So is the chair beneath you.",
          "Press two of them together and their electrons must share room.",
          "But no two electrons may occupy the same quantum state.",
          "Crowding forces some of them into higher energies. That costs.",
          "The push you feel is that cost. Not quite repulsion.",
          "It is a rule of bookkeeping, holding up your whole body.",
        ],
        footer: "The same rule holds a white dwarf against its own gravity.",
        durationSec: 30,
      },
      {
        heading: "A Hundred Trillion Ghosts A Second",
        subheading: "Solar neutrinos",
        lines: [
          "Fusion makes neutrinos: no charge, almost no mass at all.",
          "Matter hardly exists as far as they are concerned.",
          "About a hundred trillion pass through your body each second,",
          "by day and by night. At night they come up through the Earth.",
          "Light from the core needs tens of thousands of years to get out.",
          "The neutrinos leave in two seconds and arrive in eight minutes.",
        ],
        footer: "In 1987 we caught two dozen from a dying star in another galaxy.",
        durationSec: 32,
      },
      {
        heading: "Life That Divides Once A Century",
        subheading: "The deep subsurface biosphere",
        lines: [
          "Drill the seafloor and the mud is still alive a mile down.",
          "Those microbes sit in the dark with almost nothing to eat.",
          "Some are thought to divide once in a thousand years, or less often.",
          "They live on hydrogen split from water by decaying rock.",
          "Cells buried in clay laid down before the dinosaurs died",
          "have been brought up, fed in a laboratory, and they grew.",
        ],
        footer: "That clay was a hundred million years old.",
        durationSec: 32,
      },
    ],
  },
  {
    num: 8,
    slug: "archive",
    name: "THE ARCHIVE",
    kind: "archive",
    programmes: [
      {
        heading: "THE DANCING PLAGUE",
        subheading: "Strasbourg, July 1518",
        lines: [
          "A woman called Frau Troffea stepped into the street and danced.",
          "She did not stop. By the end of the week, thirty had joined her.",
          "Within a month, four hundred.",
          "Physicians ruled it was hot blood. The cure was more dancing.",
          "So the city cleared two guildhalls, built a stage, hired pipers.",
          "It burned itself out in September and never returned.",
        ],
        footer: "Cause unknown. Five centuries and counting.",
        durationSec: 32,
      },
      {
        heading: "THE GREAT EMU WAR",
        subheading: "Western Australia, November 1932",
        lines: [
          "Twenty thousand emus were walking through the wheat belt.",
          "The farmers wrote to the Defence Minister asking for machine guns.",
          "He sent two Lewis guns, ten thousand rounds, and Major Meredith.",
          "The birds broke into small scattered groups and outran the trucks.",
          "Meredith claimed 986 kills for 9,860 rounds. Ten per bird.",
          "The army withdrew. A bounty on beaks did what the guns could not.",
        ],
        footer: "\"They can face machine guns with the invulnerability of tanks.\"",
        durationSec: 32,
      },
      {
        heading: "TYCHO BRAHE KEPT AN ELK",
        subheading: "Denmark, 1591",
        lines: [
          "Tycho Brahe mapped the sky from a castle on his own island.",
          "He had a brass nose, a jester named Jepp, and a tame elk.",
          "The elk followed him like a dog and drank beer at the table.",
          "Lent out to entertain a nobleman at Landskrona Castle,",
          "it drank too much, fell down the stairs and broke a leg.",
          "Tycho reported the death in a letter to a German landgrave.",
        ],
        footer: "The elk did not recover. The star tables outlived everyone.",
        durationSec: 30,
      },
      {
        heading: "THE RADIUM GIRLS",
        subheading: "Orange, New Jersey, 1917 to 1928",
        lines: [
          "They painted glowing numbers onto watch dials by hand.",
          "To keep a fine point, they wetted the brush on their lips.",
          "Lip, dip, paint. Some painted their nails and teeth for fun.",
          "The company chemists handled the same radium from behind lead.",
          "Their jaws began to crumble. Grace Fryer hunted for a lawyer",
          "for two years. Five women sued; in 1928 they took $10,000 each.",
        ],
        footer: "Radium-226 half-life: 1,600 years. Their bones still register.",
        durationSec: 34,
      },
      {
        heading: "THE VOYNICH MANUSCRIPT",
        subheading: "Beinecke MS 408, Yale University",
        lines: [
          "Two hundred pages of calfskin, carbon dated 1404 to 1438.",
          "Plants that grow nowhere. Star charts of no known sky.",
          "Women bathing in green channels of unexplained plumbing.",
          "Twenty-odd letters, following the statistics of a real language.",
          "Rudolf the Second is said to have paid 600 gold ducats for it.",
          "Every codebreaker who has claimed it has later been wrong.",
        ],
        footer: "Not one word of it has ever been read.",
        durationSec: 30,
      },
      {
        heading: "THE YEAR WITHOUT A SUMMER",
        subheading: "1816",
        lines: [
          "Mount Tambora erupted in 1815, the largest blast on record.",
          "Its dust circled the world and turned the sun down a notch.",
          "June 1816 brought snow to New England and frost in every month.",
          "Crops failed. They called it Eighteen Hundred and Froze to Death.",
          "Rain trapped Mary Shelley indoors at Lake Geneva that summer.",
          "Feed grain ran short; in 1817 Karl Drais built the first bicycle.",
        ],
        footer: "One volcano gave us Frankenstein and the bicycle.",
        durationSec: 34,
      },
      {
        heading: "THE 1904 OLYMPIC MARATHON",
        subheading: "St. Louis, 30 August 1904",
        lines: [
          "Thirty-two men set off at noon into ninety-degree heat.",
          "Water was rationed deliberately, as an experiment in thirst.",
          "Fred Lorz rode eleven miles in a car and crossed the line first.",
          "Felix Carvajal ran in cut-off trousers and ate roadside apples.",
          "Thomas Hicks won on strychnine, raw egg and brandy, hallucinating.",
          "His trainers carried him over the line. Fourteen men finished.",
        ],
        footer: "Strychnine was legal that year. The medal still stands.",
        durationSec: 32,
      },
    ],
  },
  {
    num: 9,
    slug: "adverts",
    name: "ADVERTS",
    kind: "ad",
    programmes: [
      {
        heading: "ATOM-O-LOAF",
        subheading: "IT COOKS ITSELF! IT WAITS FOR YOU!",
        lines: [
          "Tired of ovens? Tired of waiting? Tired of Tuesday?",
          "Just pull the tab and step back eleven feet.",
          "One loaf feeds a family of four. Or a family of nine.",
          "Now in Beef, Beef-Adjacent, and Holiday Green.",
        ],
        footer: "Keep loaf away from infants and pets. Loaf may hum. This is normal.",
        durationSec: 24,
      },
      {
        heading: "THE OMNIVAC 900",
        subheading: "IT DOES NOT KNOW WHEN TO STOP!",
        lines: [
          "Twelve horsepower of genuine household suction.",
          "Picks up dirt, crumbs, pennies, keys and small rugs.",
          "Also picks up the rug pad, the floorboards, and Wednesday.",
          "Ships with a leash and a certificate of ownership.",
        ],
        footer: "Warranty void if the Omnivac is fed. Never let it see the yard.",
        durationSec: 22,
      },
      {
        heading: "GLERP!",
        subheading: "THE DRINK SCIENCE CANNOT NAME!",
        lines: [
          "One scoop. One quart of water. One unforgettable afternoon.",
          "Kids love the color. Nobody agrees on which color it is.",
          "Now with vitamins B, C, and one they are still testing.",
          "Ask your grocer. He knows. He has seen it.",
        ],
        footer: "Glerp is not a fruit product. Glerp is not the product of any fruit.",
        durationSec: 24,
      },
      {
        heading: "PERPETUAL SLACKS",
        subheading: "THEY CANNOT BE DESTROYED! WE TRIED!",
        lines: [
          "Woven from surplus bridge cable and a little bit of pride.",
          "Fireproof. Waterproof. Regret-proof.",
          "Will outlast the wearer. Will outlast the wearer's grandson.",
          "In Brown, Deep Brown, and Rumor of Brown.",
        ],
        footer: "Cannot be altered, shortened, or removed by conventional means.",
        durationSec: 24,
      },
      {
        heading: "BIG DALE'S CANYON OF CARS",
        subheading: "SUNDAY! SUNDAY! ONE DAY ONLY! MAYBE TWO!",
        lines: [
          "Two hundred automobiles standing in an actual canyon.",
          "Dale has lost his mind and also his brother's inventory.",
          "No credit? Bad credit? Dale does not check. Dale cannot read.",
          "Free hot dog with every test drive. Hot dog is not free.",
          "Take Route 9 until the road ends, then keep going.",
        ],
        footer: "Canyon is not a canyon. Dale is not a Dale. Sunday is Saturday.",
        durationSec: 28,
      },
      {
        heading: "THE COMPANION 12",
        subheading: "A FRIEND THAT NEVER LEAVES! EVER!",
        lines: [
          "Rolls into any room. Learns your name in nine seconds.",
          "Says good morning. Says good night. Says other things.",
          "Plays checkers. Plays chess. Plays favorites.",
          "It does not sleep, so you do not have to worry.",
        ],
        footer: "Unplugging the Companion 12 will not stop the Companion 12.",
        durationSec: 24,
      },
      {
        heading: "WEATHER IN A CAN",
        subheading: "THE OUTDOORS, INDOORS, ON DEMAND!",
        lines: [
          "Open a can of April right there in your living room.",
          "Six varieties: Breeze, Drizzle, Crisp, Muggy, Fog and Squall.",
          "Squall sold separately. Squall sold reluctantly.",
          "Ideal for parties, funerals, and unresolved arguments.",
        ],
        footer: "Not liable for indoor lightning. Keep Fog well away from stairs.",
        durationSec: 26,
      },
    ],
  },
  {
    num: 11,
    slug: "weather",
    name: "WEATHER",
    kind: "weather",
    programmes: [
      {
        heading: "THE MEMORY OF YOUR GRANDMOTHER'S KITCHEN",
        subheading: "Low cloud overnight. Flour in suspension.",
        lines: [
          "Overnight, low cloud over the linoleum, base three hundred feet.",
          "Steam advection from the east window, clearing by ten.",
          "Visibility poor in flour, moderate in the pantry.",
          "Wind light, backing, carrying the sound of a radio play.",
          "Warm front clears by morning. She will not be there.",
        ],
        footer: "Outlook for the following day: the same, but quieter.",
        durationSec: 27,
      },
      {
        heading: "THE FAR SIDE OF AN ARGUMENT",
        subheading: "Occluded front, slow-moving. No warning was issued.",
        lines: [
          "An occluded front lies stationary across the hallway.",
          "Cold air has been undercutting warm since about nine.",
          "Long bright intervals of being technically correct.",
          "Rain later, heavy in places, mostly in the kitchen.",
          "Pressure falling. Falling. Falling.",
        ],
        footer: "Storm names are chosen years in advance.",
        durationSec: 25,
      },
      {
        heading: "THE DROWNED VILLAGE",
        subheading: "Reservoir low. Steeple visible for the first time since 1935.",
        lines: [
          "Continued drought across the whole of the upper valley.",
          "Water level down eleven feet and still falling.",
          "The bridge is back. The road is back. The church is back.",
          "Wind light, southerly, over roofs untouched for ninety years.",
          "Fog forming at dusk in the old streets, thick and patient.",
        ],
        footer: "Rain due Thursday. Say what you came to say.",
        durationSec: 29,
      },
      {
        heading: "THE PROVINCE OF SUNDAY AFTERNOON",
        subheading: "Persistent grey. No change before Monday.",
        lines: [
          "A ridge of high pressure has parked over the whole district.",
          "Nothing will happen. That is the forecast in full.",
          "Light fails from three at a rate of one hope per hour.",
          "Homework in outlying areas remains unstarted.",
          "The bath will be run at six whether you want it or not.",
        ],
        footer: "Amber warning for the sound of the football results.",
        durationSec: 26,
      },
      {
        heading: "THE BEDROOM AT THE TOP OF THE STAIRS",
        subheading: "Clear overnight. Ceiling stars at operational strength.",
        lines: [
          "Clear skies expected across the entire duvet.",
          "Plastic constellations at eighty percent, fading by two.",
          "Landing light steady from the west, door ajar as agreed.",
          "Isolated monsters confined to the wardrobe. No movement.",
          "Sea state calm. Adults audible below, which is the point.",
        ],
        footer: "These conditions have since been withdrawn from service.",
        durationSec: 28,
      },
      {
        heading: "THE MOTORWAY AT THREE IN THE MORNING",
        subheading: "Fog patches. Radio reception intermittent.",
        lines: [
          "Freezing fog in the hollows between junctions nine and twelve.",
          "Visibility fifty metres, less beneath the bridges.",
          "One other vehicle on the network. It is keeping pace.",
          "Services at the next junction: lit, staffed, empty.",
          "Dawn is a rumour reported by drivers further east.",
        ],
        footer: "You are not tired. You are three hundred miles from tired.",
        durationSec: 29,
      },
      {
        heading: "THE FIRST FOURTEEN DAYS",
        subheading: "Unseasonable warmth. Records expected to fall.",
        lines: [
          "A remarkable ridge of high pressure over the entire body.",
          "Temperatures ten degrees above average and climbing.",
          "No cloud. None. The instruments were checked twice.",
          "Light winds veering, carrying the smell of somebody's coat.",
          "Models diverge sharply after the fourteenth day.",
        ],
        footer: "This bulletin will not be repeated. Go outside.",
        durationSec: 27,
      },
    ],
  },
  {
    num: 12,
    slug: "shorts",
    name: "SHORTS",
    kind: "shortfic",
    programmes: [
      {
        heading: "THE COUNT",
        subheading: "night shift, Redmond Street Garage",
        lines: [
          "Milo counted cars for eleven years.",
          "In at the gate, out at the ramp.",
          "The numbers always closed by dawn.",
          "On a Tuesday in March they did not.",
          "One car was still on level six.",
          "He climbed with his flashlight,",
          "past empty bay after empty bay,",
          "and found it in the corner: his own.",
          "Same dent. Same rosary on the mirror.",
          "The engine was still warm.",
          "Milo does not own a car.",
          "He sold it the spring his wife died",
          "and has walked to work ever since.",
          "He got in. It smelled like her.",
          "The count closed at dawn.",
        ],
        footer: "The garage has five levels.",
        durationSec: 32,
      },
      {
        heading: "THURSDAYS",
        subheading: "school lets out at three",
        lines: [
          "Every Thursday the boy is the last one.",
          "The janitor mops around his sneakers",
          "and pretends not to watch the clock.",
          "At six he says, I'm going for coffee.",
          "Keep me company?",
          "They walk to the gas station.",
          "He buys two hot chocolates",
          "and calls one of them coffee",
          "so the boy can feel grown.",
          "By the time they get back",
          "the mother's headlights are turning in,",
          "apologizing before she's out of the car.",
          "No trouble, he says. He's good company.",
          "Nineteen years later the boy buys two",
          "coffees a week, and calls one cocoa.",
        ],
        footer: "The janitor never knew. That's the deal.",
        durationSec: 32,
      },
      {
        heading: "NOTICE TO RESIDENTS",
        subheading: "posted in the lobby, no date",
        lines: [
          "Someone has been leaving casseroles",
          "outside apartment 4C.",
          "4C has been empty since April.",
          "Management thanks you for your concern",
          "but must ask that this stop.",
          "The hallway smells of mushroom soup.",
          "UPDATE: the casseroles continue.",
          "UPDATE: a note appeared under the door",
          "reading THANK YOU in blue crayon.",
          "No child lives in this building.",
          "Management has stopped investigating.",
          "Management has begun leaving a plate",
          "out on Sundays. Just in case.",
        ],
        footer: "Please label your dishes.",
        durationSec: 26,
      },
      {
        heading: "DAY 400",
        subheading: "a transmission, unanswered",
        lines: [
          "The station lost contact on day 400.",
          "Protocol says keep broadcasting.",
          "So Ilya read the manual aloud.",
          "Then the labels on the food packets.",
          "Then, when those ran out,",
          "he described the Earth as it turned:",
          "storms over Chile, the ice going,",
          "the lights of cities he'd never walk in.",
          "He talked for eleven months.",
          "Nothing ever answered.",
          "On the last day he said,",
          "I have been very happy up here,",
          "which was a lie, and then,",
          "I have not been lonely,",
          "which was not.",
        ],
        footer: "Recovered from the drift, 2061.",
        durationSec: 32,
      },
      {
        heading: "THE UNDERSTUDY",
        subheading: "Palace Theatre, closed",
        lines: [
          "For thirty-one years Dolores understood",
          "that Margot would never miss a show.",
          "Flu, funerals, a broken wrist in '88.",
          "Margot went on.",
          "Dolores learned every line",
          "and sat in the wings in full costume",
          "like a coin nobody ever spent.",
          "The night Margot finally died,",
          "the theatre was already dark:",
          "sold to a bank the previous June.",
          "Dolores put on the dress anyway.",
          "She stood in the marble lobby,",
          "under the light of the ATM,",
          "and gave the whole play to the windows.",
          "She was magnificent.",
        ],
        footer: "There is no one alive to say otherwise.",
        durationSec: 34,
      },
      {
        heading: "SIX KNOCKS",
        subheading: "the first rule they teach the children",
        lines: [
          "The town of Ash Fork has one rule.",
          "If you hear knocking after midnight,",
          "count it.",
          "Three knocks is the wind.",
          "Four is a neighbor with bad news.",
          "Five, you may open the door.",
          "Nobody in Ash Fork can tell you",
          "what happens at six,",
          "because everyone who has heard six",
          "answered on five, out of habit,",
          "and was found the next morning",
          "sitting up in bed, perfectly well,",
          "and perfectly unable to remember",
          "anyone who had ever loved them.",
          "So count. Take your time.",
        ],
        footer: "It will wait as long as you do.",
        durationSec: 34,
      },
      {
        heading: "THE GOOSE",
        subheading: "filed with the parks department, unread",
        lines: [
          "For six years I hated a goose.",
          "It lived by the pond on Ferrand Street",
          "and it hated me with professionalism.",
          "It bit my briefcase. It bit my son.",
          "It once chased me into a Wendy's.",
          "I called the city eleven times.",
          "The city sent a man who looked once",
          "and said, that is not a goose I can move.",
          "This spring the pond was quiet.",
          "Somebody said a fox. Somebody said age.",
          "I stood there a long while",
          "holding a bagel I didn't have to defend,",
          "and I found, to my inconvenience,",
          "that I missed him.",
        ],
        footer: "Rest easy, you terrible bird.",
        durationSec: 32,
      },
    ],
  },
  {
    num: 13,
    slug: "signoff",
    name: "NIGHT",
    kind: "ambient",
    programmes: [
      {
        heading: "TEST CARD",
        subheading: "Channel 13. Transmission continues.",
        lines: [
          "Bars from white to black. Tone at one kilohertz.",
          "This card exists so an engineer can find a fault.",
          "There is no fault tonight. There is only the hour.",
          "Adjust nothing. You are receiving us correctly.",
        ],
        footer: "Held until programming resumes.",
        durationSec: 26,
      },
      {
        heading: "STATION IDENTIFICATION",
        subheading: "NIGHT. Thirteen on the dial.",
        lines: [
          "This is Channel 13, broadcasting from a low hill.",
          "Four hundred watts. Enough for the valley, and you.",
          "We never learn how many are watching, so we assume one.",
        ],
        footer: "Good evening to that one.",
        durationSec: 20,
      },
      {
        heading: "TO THE STILL AWAKE",
        subheading: "A word for the small hours",
        lines: [
          "You did not choose to be up. We know that.",
          "Nothing needs deciding before morning. Nothing.",
          "The list you are holding will still exist at eight.",
          "Put it on the floor beside the bed for now.",
        ],
        footer: "We keep the screen lit either way.",
        durationSec: 28,
      },
      {
        heading: "THE QUIET HOUR",
        subheading: "Observed nightly, three to four",
        lines: [
          "Between three and four the traffic stops entirely.",
          "Fridges become the loudest machines in the country.",
          "Every house runs one, humming the same low note.",
          "It is the largest choir nobody has ever heard.",
          "You are, right now, sitting inside it.",
        ],
        footer: "This has been an observation.",
        durationSec: 34,
      },
      {
        heading: "NIGHT STAFF",
        subheading: "One building, three lights on",
        lines: [
          "A man here is paid to watch the needles move.",
          "They have not moved since eleven o'clock.",
          "He has a flask of tea and a paperback with a bent spine.",
          "He says hello. That is the whole of the bulletin.",
        ],
        footer: "He goes home when the birds start.",
        durationSec: 29,
      },
      {
        heading: "OVERNIGHT CONDITIONS",
        subheading: "Issued at half past two",
        lines: [
          "Clear. Cold on the roofs. No wind worth the word.",
          "Fog forming in the low fields by four.",
          "One aircraft crossing, too high up to hear.",
          "Moon at three quarters, doing its usual work.",
        ],
        footer: "Nothing is coming. Sleep is safe to attempt.",
        durationSec: 30,
      },
      {
        heading: "CLOSEDOWN",
        subheading: "Which we will not be doing",
        lines: [
          "Other stations play the anthem and pull the switch.",
          "We tried it once. The silence was worse than the hour.",
          "So Channel 13 stays up. Low light, low volume.",
          "If you wake again at five, we will still be here.",
        ],
        footer: "Transmission continues. Goodnight anyway.",
        durationSec: 33,
      },
    ],
  },
];
