import type { Programme } from '../types';

/**
 * CHANNEL 14 — MATINEE. The one channel that broadcasts real film.
 *
 * Thirty clips from six public-domain pictures, all of them in a single 6MB
 * file. That is the one-reel technique: every programme points at the same
 * `src` with a different `reelOffsetSec`, so changing segment is a seek
 * rather than a load. Browsers never block a seek, so there is no black frame
 * between clips and no second permission prompt for audio.
 *
 * The footage is public domain, from the Internet Archive by way of
 * jesseweb.com (MIT, Jesse M. Torres) — see the credits in the README. The
 * clips were re-cut from that project's broadcast reel, keeping only the
 * segments whose film can actually be named.
 *
 * This channel has no entry in `beds.data.ts`, deliberately: the films have
 * their own soundtrack and an ambient bed underneath would be fighting it.
 */

export const MATINEE_SRC = '/media/matinee.mp4';

export const MATINEE: Programme[] = [
  {
    id: "matinee-00",
    kind: 'scene',
    heading: "House on Haunted Hill",
    subheading: "1959 · reel 1 of 5",
    lines: ["Vincent Price offers five strangers ten thousand dollars to stay the night. William Castle directs."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 0 },
  },
  {
    id: "matinee-01",
    kind: 'scene',
    heading: "House on Haunted Hill",
    subheading: "1959 · reel 2 of 5",
    lines: ["Vincent Price offers five strangers ten thousand dollars to stay the night. William Castle directs."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 13.9 },
  },
  {
    id: "matinee-02",
    kind: 'scene',
    heading: "House on Haunted Hill",
    subheading: "1959 · reel 3 of 5",
    lines: ["Vincent Price offers five strangers ten thousand dollars to stay the night. William Castle directs."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 27.8 },
  },
  {
    id: "matinee-03",
    kind: 'scene',
    heading: "House on Haunted Hill",
    subheading: "1959 · reel 4 of 5",
    lines: ["Vincent Price offers five strangers ten thousand dollars to stay the night. William Castle directs."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 41.7 },
  },
  {
    id: "matinee-04",
    kind: 'scene',
    heading: "House on Haunted Hill",
    subheading: "1959 · reel 5 of 5",
    lines: ["Vincent Price offers five strangers ten thousand dollars to stay the night. William Castle directs."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 55.6 },
  },
  {
    id: "matinee-05",
    kind: 'scene',
    heading: "The Giant Gila Monster",
    subheading: "1959 · reel 1 of 5",
    lines: ["A drive-in monster picture in which the monster is a real lizard walking on a model town."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 69.5 },
  },
  {
    id: "matinee-06",
    kind: 'scene',
    heading: "The Giant Gila Monster",
    subheading: "1959 · reel 2 of 5",
    lines: ["A drive-in monster picture in which the monster is a real lizard walking on a model town."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 83.4 },
  },
  {
    id: "matinee-07",
    kind: 'scene',
    heading: "The Giant Gila Monster",
    subheading: "1959 · reel 3 of 5",
    lines: ["A drive-in monster picture in which the monster is a real lizard walking on a model town."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 97.3 },
  },
  {
    id: "matinee-08",
    kind: 'scene',
    heading: "The Giant Gila Monster",
    subheading: "1959 · reel 4 of 5",
    lines: ["A drive-in monster picture in which the monster is a real lizard walking on a model town."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 111.2 },
  },
  {
    id: "matinee-09",
    kind: 'scene',
    heading: "The Giant Gila Monster",
    subheading: "1959 · reel 5 of 5",
    lines: ["A drive-in monster picture in which the monster is a real lizard walking on a model town."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 125.1 },
  },
  {
    id: "matinee-10",
    kind: 'scene',
    heading: "Popeye Meets Sindbad the Sailor",
    subheading: "1936 · reel 1 of 5",
    lines: ["Fleischer again, in three-strip Technicolor and their stereoptical process. Genuinely beautiful."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 139 },
  },
  {
    id: "matinee-11",
    kind: 'scene',
    heading: "Popeye Meets Sindbad the Sailor",
    subheading: "1936 · reel 2 of 5",
    lines: ["Fleischer again, in three-strip Technicolor and their stereoptical process. Genuinely beautiful."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 152.9 },
  },
  {
    id: "matinee-12",
    kind: 'scene',
    heading: "Popeye Meets Sindbad the Sailor",
    subheading: "1936 · reel 3 of 5",
    lines: ["Fleischer again, in three-strip Technicolor and their stereoptical process. Genuinely beautiful."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 166.8 },
  },
  {
    id: "matinee-13",
    kind: 'scene',
    heading: "Popeye Meets Sindbad the Sailor",
    subheading: "1936 · reel 4 of 5",
    lines: ["Fleischer again, in three-strip Technicolor and their stereoptical process. Genuinely beautiful."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 180.7 },
  },
  {
    id: "matinee-14",
    kind: 'scene',
    heading: "Popeye Meets Sindbad the Sailor",
    subheading: "1936 · reel 5 of 5",
    lines: ["Fleischer again, in three-strip Technicolor and their stereoptical process. Genuinely beautiful."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 194.6 },
  },
  {
    id: "matinee-15",
    kind: 'scene',
    heading: "The Phantom Planet",
    subheading: "1961 · reel 1 of 5",
    lines: ["A stranded astronaut shrinks to six inches on an asteroid that has opinions about him."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 208.5 },
  },
  {
    id: "matinee-16",
    kind: 'scene',
    heading: "The Phantom Planet",
    subheading: "1961 · reel 2 of 5",
    lines: ["A stranded astronaut shrinks to six inches on an asteroid that has opinions about him."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 222.4 },
  },
  {
    id: "matinee-17",
    kind: 'scene',
    heading: "The Phantom Planet",
    subheading: "1961 · reel 3 of 5",
    lines: ["A stranded astronaut shrinks to six inches on an asteroid that has opinions about him."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 236.3 },
  },
  {
    id: "matinee-18",
    kind: 'scene',
    heading: "The Phantom Planet",
    subheading: "1961 · reel 4 of 5",
    lines: ["A stranded astronaut shrinks to six inches on an asteroid that has opinions about him."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 250.2 },
  },
  {
    id: "matinee-19",
    kind: 'scene',
    heading: "The Phantom Planet",
    subheading: "1961 · reel 5 of 5",
    lines: ["A stranded astronaut shrinks to six inches on an asteroid that has opinions about him."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 264.1 },
  },
  {
    id: "matinee-20",
    kind: 'scene',
    heading: "Variety Tonight",
    subheading: "1950 · reel 1 of 5",
    lines: ["The Jack Benny Program and You Bet Your Life. Television learning what it was for."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 278 },
  },
  {
    id: "matinee-21",
    kind: 'scene',
    heading: "Variety Tonight",
    subheading: "1950 · reel 2 of 5",
    lines: ["The Jack Benny Program and You Bet Your Life. Television learning what it was for."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 291.9 },
  },
  {
    id: "matinee-22",
    kind: 'scene',
    heading: "Variety Tonight",
    subheading: "1950 · reel 3 of 5",
    lines: ["The Jack Benny Program and You Bet Your Life. Television learning what it was for."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 305.8 },
  },
  {
    id: "matinee-23",
    kind: 'scene',
    heading: "Variety Tonight",
    subheading: "1950 · reel 4 of 5",
    lines: ["The Jack Benny Program and You Bet Your Life. Television learning what it was for."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 319.7 },
  },
  {
    id: "matinee-24",
    kind: 'scene',
    heading: "Variety Tonight",
    subheading: "1950 · reel 5 of 5",
    lines: ["The Jack Benny Program and You Bet Your Life. Television learning what it was for."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 333.6 },
  },
  {
    id: "matinee-25",
    kind: 'scene',
    heading: "Superman vs. The Mechanical Monsters",
    subheading: "1941 · reel 1 of 5",
    lines: ["Fleischer Studios. Rotoscoped robots, art deco skylines, and the best-looking cartoon of its decade."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 347.5 },
  },
  {
    id: "matinee-26",
    kind: 'scene',
    heading: "Superman vs. The Mechanical Monsters",
    subheading: "1941 · reel 2 of 5",
    lines: ["Fleischer Studios. Rotoscoped robots, art deco skylines, and the best-looking cartoon of its decade."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 361.4 },
  },
  {
    id: "matinee-27",
    kind: 'scene',
    heading: "Superman vs. The Mechanical Monsters",
    subheading: "1941 · reel 3 of 5",
    lines: ["Fleischer Studios. Rotoscoped robots, art deco skylines, and the best-looking cartoon of its decade."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 375.3 },
  },
  {
    id: "matinee-28",
    kind: 'scene',
    heading: "Superman vs. The Mechanical Monsters",
    subheading: "1941 · reel 4 of 5",
    lines: ["Fleischer Studios. Rotoscoped robots, art deco skylines, and the best-looking cartoon of its decade."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 389.2 },
  },
  {
    id: "matinee-29",
    kind: 'scene',
    heading: "Superman vs. The Mechanical Monsters",
    subheading: "1941 · reel 5 of 5",
    lines: ["Fleischer Studios. Rotoscoped robots, art deco skylines, and the best-looking cartoon of its decade."],
    footer: '',
    durationSec: 14,
    media: { src: MATINEE_SRC, reelOffsetSec: 403.1 },
  },
];
